// <auto-generated />
using System;
using Auth.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Auth.Migrations
{
    [DbContext(typeof(PersonContext))]
    [Migration("20230331172110_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Auth.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdType")
                        .HasColumnType("int");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cliente", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("71c87875-4439-4d7c-ba96-f8ba9136dba2"),
                            Email = "aagrzada@gmail.com",
                            FechaCreado = new DateTime(2023, 3, 31, 12, 21, 10, 731, DateTimeKind.Local).AddTicks(6397),
                            IdType = 0,
                            Identification = "8-873-000",
                            Name = "Alexander Agrazal",
                            Phonenumber = "12345",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("71c87875-4439-4d7c-ba96-f8ba9136dba3"),
                            Email = "hdegracia@gmail.com",
                            FechaCreado = new DateTime(2023, 3, 31, 12, 21, 10, 731, DateTimeKind.Local).AddTicks(6403),
                            IdType = 0,
                            Identification = "8-000-387",
                            Name = "Hector De Gracia",
                            Phonenumber = "12345",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Auth.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdType")
                        .HasColumnType("int");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("71c87875-4439-4d7c-ba96-f8ba9136dbaa"),
                            Email = "ckomalram@gmail.com",
                            FechaCreado = new DateTime(2023, 3, 31, 12, 21, 10, 731, DateTimeKind.Local).AddTicks(5272),
                            IdType = 0,
                            Identification = "8-873-387",
                            Name = "Carlyle Komalram",
                            Password = "12345",
                            Role = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("71c87875-4439-4d7c-ba96-f8ba9136dba1"),
                            Email = "yoainaris@gmail.com",
                            FechaCreado = new DateTime(2023, 3, 31, 12, 21, 10, 731, DateTimeKind.Local).AddTicks(5292),
                            IdType = 0,
                            Identification = "8-920-953",
                            Name = "Yoainaris Concepcion",
                            Password = "12345",
                            Role = 0,
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
